Book.destroy_all

Book.create!([
  {title: "The Hitchhiker's Guide To The Galaxy", author: "Douglas Adams", preview_url: "http://res.cloudinary.com/dkefwablr/raw/upload/v1505761957/h2g2.pdf", image_url: "https://i.imgur.com/DnbT4KB.jpg", publisher: "Del Rey", description: "Seconds before Earth is demolished to make way for a galactic freeway, Arthur Dent is plucked off the planet by his friend Ford Prefect, a researcher for the revised edition of The Hitchhiker’s Guide to the Galaxy who, for the last fifteen years, has been posing as an out-of-work actor.\n\nTogether, this dynamic pair began a journey through space aided by a galaxyful of fellow travelers: Zaphod Beeblebrox, the two-headed, three-armed, ex-hippie and totally out-to-lunch president of the galaxy; Trillian (formerly Tricia McMillan), Zaphod’s girlfriend, whom Arthur tried to pick up at a cocktail party once upon a time zone; Marvin, a paranoid, brilliant, and chronically depressed robot; and Veet Voojagig, a former graduate student obsessed with the disappearance of all the ballpoint pens he’s bought over the years.\n\nWhere are these pens? Why are we born? Why do we die? For all the answers, stick your thumb to the stars!"},
  {title: "Slaughterhouse-Five", author: "Kurt Vonnegut", preview_url: "http://res.cloudinary.com/dkefwablr/raw/upload/v1505737654/sh5.pdf", image_url: "https://i.imgur.com/8pbh3jO.jpg", publisher: "Dial Press Trade Paperback", description: "Kurt Vonnegut's absurdist classic Slaughterhouse-Five introduces us to Billy Pilgrim, a man who becomes unstuck in time after he is abducted by aliens from the planet Tralfamadore. In a plot-scrambling display of virtuosity, we follow Pilgrim simultaneously through all phases of his life, concentrating on his (and Vonnegut's) shattering experience as an American prisoner of war who witnesses the firebombing of Dresden.\n\nDon't let the ease of reading fool you - Vonnegut's isn't a conventional, or simple, novel. He writes, There are almost no characters in this story, and almost no dramatic confrontations, because most of the people in it are so sick, and so much the listless playthings of enormous forces. One of the main effects of war, after all, is that people are discouraged from being characters.\n\nSlaughterhouse-Five is not only Vonnegut's most powerful book, it is also as important as any written since 1945. Like Catch- 22, it fashions the author's experiences in the Second World War into an eloquent and deeply funny plea against butchery in the service of authority. Slaughterhouse-Five boasts the same imagination, humanity, and gleeful appreciation of the absurd found in Vonnegut's other works, but the book's basis in rock-hard, tragic fact gives it a unique poignancy - and humor."},
  {title: "Ubik", author: "Philip K. Dick", image_url: "https://i.imgur.com/6Zeayhh.jpg", publisher: "Bantam Books", description: "Ubik is a 1969 science fiction novel by American writer Philip K. Dick. It is one of Dick's most acclaimed novels. It was chosen by Time magazine as one of the 100 greatest novels since 1923. In his review for Time, critic Lev Grossman described it as a deeply unsettling existential horror story, a nightmare you'll never be sure you've woken up from.\n\nThe novel takes place in the North American Confederation of 1992, where civilians regularly travel to the Moon, and psi phenomena are common. The novel's protagonist, Joe Chip, is a debt-ridden technician for Glen Runciter's prudence organization, which employs people with the ability to block psychic powers (like an anti-telepath, preventing a telepath from reading a mind) to help enforce privacy. Runciter runs the company with the assistance of his deceased wife Ella, who is kept in a state of half-life, a form of cryonic suspension that gives the deceased limited consciousness and the ability to communicate."},
  {title: "All You Need Is Kill", author: "Hiroshi Sakurazaka", image_url: "https://i.imgur.com/9u199q8.jpg", publisher: "Haikasoru", description: "There’s one thing worse than dying. It’s coming back to do it again and again… When the alien Gitai invade, Keiji Kiriya is just one of many raw recruits shoved into a suit of battle armor and sent out to kill. Keiji dies on the battlefield, only to find himself reborn each morning to fight and die again and again. On the 158th iteration though, he sees something different, something out of place: the female soldier known as the Witch of War. Is the Witch the key to Keiji’s escape, or to his final death?"},
  {title: "Harry Potter and the Sorcerer's Stone", author: "J.K. Rowling", image_url: "https://i.imgur.com/h2lCssT.jpg", publisher: "Scholastic Inc", description: "Harry Potter's life is miserable. His parents are dead and he's stuck with his heartless relatives, who force him to live in a tiny closet under the stairs. But his fortune changes when he receives a letter that tells him the truth about himself: he's a wizard. A mysterious visitor rescues him from his relatives and takes him to his new home, Hogwarts School of Witchcraft and Wizardry.\n\nAfter a lifetime of bottling up his magical powers, Harry finally feels like a normal kid. But even within the Wizarding community, he is special. He is the boy who lived: the only person to have ever survived a killing curse inflicted by the evil Lord Voldemort, who launched a brutal takeover of the Wizarding world, only to vanish after failing to kill Harry.\n\nThough Harry's first year at Hogwarts is the best of his life, not everything is perfect. There is a dangerous secret object hidden within the castle walls, and Harry believes it's his responsibility to prevent it from falling into evil hands. But doing so will bring him into contact with forces more terrifying than he ever could have imagined.\n\nFull of sympathetic characters, wildly imaginative situations, and countless exciting details, the first installment in the series assembles an unforgettable magical world and sets the stage for many high-stakes adventures to come."},
  {title: "The Caves of Steel", author: "Isaac Asimov", image_url: "https://i.imgur.com/XGxTgmj.jpg", publisher: "Voyager", description: "A millennium into the future two advancements have altered the course of human history: the colonization of the galaxy and the creation of the positronic brain. Isaac Asimov's Robot novels chronicle the unlikely partnership between a New York City detective and a humanoid robot who must learn to work together. Like most people left behind on an over-populated Earth, New York City police detective Elijah Baley had little love for either the arrogant Spacers or their robotic companions. But when a prominent Spacer is murdered under mysterious circumstances, Baley is ordered to the Outer Worlds to help track down the killer. The relationship between Life and his Spacer superiors, who distrusted all Earthmen, was strained from the start. Then he learned that they had assigned him a partner: R. Daneel Olivaw. Worst of all was that the 'R' stood for robot--and his positronic partner was made in the image and likeness of the murder victim!"},
  {title: "Console Wars: Sega, Nintendo, and the Battle that Defined a Generation", author: "Blake J. Harris", image_url: "https://i.imgur.com/FqUrwSo.jpg", publisher: "It Books", description: "Following the success of The Accidental Billionaires and Moneyball comes Console Wars—a mesmerizing, behind-the-scenes business thriller that chronicles how Sega, a small, scrappy gaming company led by an unlikely visionary and a team of rebels, took on the juggernaut Nintendo and revolutionized the video game industry.\n\nIn 1990, Nintendo had a virtual monopoly on the video game industry. Sega, on the other hand, was just a faltering arcade company with big aspirations and even bigger personalities. But that would all change with the arrival of Tom Kalinske, a man who knew nothing about videogames and everything about fighting uphill battles. His unconventional tactics, combined with the blood, sweat and bold ideas of his renegade employees, transformed Sega and eventually led to a ruthless David-and-Goliath showdown with rival Nintendo.\n\nThe battle was vicious, relentless, and highly profitable, eventually sparking a global corporate war that would be fought on several fronts: from living rooms and schoolyards to boardrooms and Congress. It was a once-in-a-lifetime, no-holds-barred conflict that pitted brother against brother, kid against adult, Sonic against Mario, and the US against Japan.\n\nBased on over two hundred interviews with former Sega and Nintendo employees, Console Wars is the underdog tale of how Kalinske miraculously turned an industry punchline into a market leader. It's the story of how a humble family man, with an extraordinary imagination and a gift for turning problems into competitive advantages, inspired a team of underdogs to slay a giant and, as a result, birth a $60 billion dollar industry."},
  {title: "BioShock: Rapture", author: "John Shirley", image_url: "https://i.imgur.com/3QPn1oA.jpg", publisher: "Tor Books", description: "It's the end of World War II. FDR's New Deal has redefined American politics. Taxes are at an all-time high. The bombing of Hiroshima and Nagasaki has brought a fear of total annihilation. The rise of secret government agencies and sanctions on business has many watching their backs. America's sense of freedom is diminishing . . . and many are desperate to take that freedom back.\n\nAmong them is a great dreamer, an immigrant who pulled himself from the depths of poverty to become one of the wealthiest and admired men in the world. That man is Andrew Ryan, and he believed that great men and women deserve better. And so he set out to create the impossible, a utopia free from government, censorship, and moral restrictions on science--where what you give is what you get. He created Rapture---the shining city below the sea.\n\nBut as we all know, this utopia suffered a great tragedy. This is the story of how it all came to be . . .and how it all ended."},
  {title: "In a Grove", author: "Ryunosuke Akutagawa", image_url: "https://i.imgur.com/TGfkxMr.jpg", publisher: "Kodansha", description: "'In a Grove' (藪の中, Yabu no Naka?) is a short story by Ryūnosuke Akutagawa, first appearing in the January 1922 edition of the Japanese literature monthly Shinchō. Akira Kurosawa used this story as the basis for his award-winning movie Rashōmon.\n\n'In a Grove' is an early modernist short story consisting of seven varying accounts of the murder of a samurai, Kanazawa no Takehiro, whose corpse has been found in a bamboo forest near Kyoto. Each section simultaneously clarifies and obfuscates what the reader knows about the murder, eventually creating a complex and contradictory vision of events that brings into question humanity's ability or willingness to perceive and transmit objective truth.\n\nThe story is often praised as being among the greatest in Japanese literature."},
  {title: "A Game of Thrones", author: "George R.R. Martin", image_url: "https://i.imgur.com/aa0ocZw.jpg", publisher: "Bantam", description: "Summers span decades. Winter can last a lifetime. And the struggle for the Iron Throne has begun.\n\nAs Warden of the north, Lord Eddard Stark counts it a curse when King Robert bestows on him the office of the Hand. His honour weighs him down at court where a true man does what he will, not what he must … and a dead enemy is a thing of beauty.\n\nThe old gods have no power in the south, Stark’s family is split and there is treachery at court. Worse, the vengeance-mad heir of the deposed Dragon King has grown to maturity in exile in the Free Cities. He claims the Iron Throne."},
  {title: "The Eye of the World", author: "Robert Jordan", image_url: "https://i.imgur.com/MivrVjT.jpg", publisher: "Tor Books", description: "The Wheel of Time turns and Ages come and go, leaving memories that become legend. Legend fades to myth, and even myth is long forgotten when the Age that gave it birth returns again. In the Third Age, an Age of Prophecy, the World and Time themselves hang in the balance. What was, what will be, and what is, may yet fall under the Shadow."},
  {title: "The Man in the High Castle", author: "Philip K. Dick", image_url: "https://i.imgur.com/2mytIvj.jpg", publisher: "Vintage", description: "It's America in 1962. Slavery is legal once again. The few Jews who still survive hide under assumed names. In San Francisco the I Ching is as common as the Yellow Pages. All because some 20 years earlier the United States lost a war, and is now occupied jointly by Nazi Germany and Japan. This harrowing, Hugo Award-winning novel is the work that established Philip K. Dick as an innovator in science fiction while breaking the barrier between science fiction and the serious novel of ideas. In it Dick offers a haunting vision of history as a nightmare from which it may just be possible to awake."},
  {title: "Machine of Death", author: "Ryan North", image_url: "https://i.imgur.com/P6c4Nvn.jpg", publisher: "Machines of Death", description: "The machine had been invented a few years ago: a machine that could tell, from just a sample of your blood, how you were going to die. It didn't give you the date and it didn't give you specifics. It just spat out a sliver of paper upon which were printed, in careful block letters, the words DROWNED or CANCER or OLD AGE or CHOKED ON A HANDFUL OF POPCORN. It let people know how they were going to die. Machine of Death tells thirty-four different stories about people who know how they will die. Prepare to have your tears jerked, your spine tingled, your funny bone tickled, your mind blown, your pulse quickened, or your heart warmed. Or better yet, simply prepare to be surprised. Because even when people do have perfect knowledge of the future, there's no telling exactly how things will turn out."},
  {title: "Dirk Gently's Holistic Detective Agency", author: "Douglas Adams", image_url: "https://i.imgur.com/VV06VwS.jpg", publisher: "Pocket Books", description: "What do a dead cat, a computer whiz-kid, an Electric Monk who believes the world is pink, quantum mechanics, a Chronologist over 200 years old, Samuel Taylor Coleridge (poet), and pizza have in common? Apparently not much; until Dirk Gently, self-styled private investigator, sets out to prove the fundamental interconnectedness of all things by solving a mysterious murder, assisting a mysterious professor, unravelling a mysterious mystery, and eating a lot of pizza – not to mention saving the entire human race from extinction along the way (at no extra charge). To find out more, read this book (better still, buy it, then read it) – or contact Dirk Gently’s Holistic Detective Agency. ‘A thumping good detective-ghost-horror-whodunnit-time travel-romantic-musical-comedy epic."},
  {title: "The New York Trilogy", author: "Paul Auster", image_url: "https://i.imgur.com/CUvZwS7.jpg", publisher: "Penguin Classics", description: "Paul Auster's signature work, The New York Trilogy, consists of three interlocking novels: City of Glass, Ghosts, and The Locked Room; haunting and mysterious tales that move at the breathless pace of a thriller."},
  {title: "Stardust", author: "Neil Gaiman", image_url: "https://i.imgur.com/kfQTdeL.jpg", publisher: "Harper Perrennial", description: "Young Tristran Thorn will do anything to win the cold heart of beautiful Victoria—even fetch her the star they watch fall from the night sky. But to do so, he must enter the unexplored lands on the other side of the ancient wall that gives their tiny village its name. Beyond that old stone wall, Tristran learns, lies Faerie—where nothing, not even a fallen star, is what he imagined. From #1 New York Times bestselling author Neil Gaiman comes a remarkable quest into the dark and miraculous—in pursuit of love and the utterly impossible."},
  {title: "American Gods", author: "Neil Gaiman", image_url: "https://i.imgur.com/h6csv6I.jpg", publisher: "William Morrow", description: "Locked behind bars for three years, Shadow did his time, quietly waiting for the day when he could return to Eagle Point, Indiana. A man no longer scared of what tomorrow might bring, all he wanted was to be with Laura, the wife he deeply loved, and start a new life. But just days before his release, Laura and Shadow's best friend are killed in an accident. With his life in pieces and nothing to keep him tethered, Shadow accepts a job from a beguiling stranger he meets on the way home, an enigmatic man who calls himself Mr. Wednesday. A trickster and a rogue, Wednesday seems to know more about Shadow than Shadow does himself. Life as Wednesday's bodyguard, driver, and errand boy is far more interesting and dangerous than Shadow ever imagined. Soon Shadow learns that the past never dies...and that beneath the placid surface of everyday life a storm is brewing - an epic war for the very soul of America - and that he is standing squarely in its path."},
  {title: "Parasyte, Volume 1", author: "Hitoshi Iwaaki", image_url: "https://i.imgur.com/7VV5EF1.jpg", publisher: "Del Rey", description: "They arrive in silence and darkness. They descend from the skies. They have a hunger for human flesh. They are everywhere. They are parasites, alien creatures who must invade - and take control of - a human host to survive. And once they have infected their victims, they can assume any deadly form they choose: monsters with giant teeth, winged demons, creatures with blades for hands. But most have chosen to conceal their lethal purpose behind ordinary human faces. So no one knows their secret - except an ordinary high school student. Shin is battling for control of his own body against an alien parasite, but can he find a way to warn humanity of the horrors to come?"},
  {title: "Mass Effect: Revelation", author: "Drew Karpyshyn", image_url: "https://i.imgur.com/33mNAFw.jpg", publisher: "Del Rey", description: "Every advanced society in the galaxy relies on the technology of the Protheans, an ancient species that vanished fifty thousand years ago. After discovering a cache of Prothean technology on Mars in 2148, humanity is spreading to the stars; the newest interstellar species, struggling to carve out its place in the greater galactic community. On the edge of colonized space, ship commander and Alliance war hero David Anderson investigates the remains of a top secret military research station; smoking ruins littered with bodies and unanswered questions. Who attacked this post and for what purpose? And where is Kahlee Sanders, the young scientist who mysteriously vanished from the base hours before her colleagues were slaughtered? Sanders is now the prime suspect, but finding her creates more problems for Anderson than it solves. Partnered with a rogue alien agent he can't trust and pursued by an assassin he can't escape, Anderson battles impossible odds on uncharted worlds to uncover a sinister conspiracy . . . one he won't live to tell about. Or so the enemy thinks."},
  {title: "Gears of War: Aspho Fields", author: "Karen Traviss", image_url: "https://i.imgur.com/XWhcHUJ.jpg", publisher: "Del Rey", description: "For the first time, fans of the blockbuster Gears of War video games get an in-depth look at Delta Squad’s toughest fighters–soldier’s soldier Marcus Fenix and rock-solid Dominic Santiago–as well as a detailed account of the pivotal battle of the Pendulum Wars. As kids, the three of them were inseparable; as soldiers, they were torn apart. Marcus Fenix and Dominic Santiago fought alongside Dom’s elder brother Carlos at Aspho Fields in the epic battle that changed the course of the Pendulum Wars. There’s a new war to fight now, a war for mankind’s very survival. But while the last human stronghold on Sera braces itself for another onslaught from the Locust Horde, ghosts come back to haunt Marcus and Dom. For Marcus–decorated war hero, convicted traitor–the return of an old comrade threatens to dredge up an agonizing secret he’s sworn to keep. As the beleaguered Gears of the Coalition of Ordered Governments take a Last Stand to save mankind from extermination, the harrowing decisions made at Aspho Fields have to be re-lived and made again. Marcus and Dom can take anything the Locust Horde throws at them–but will their friendship survive the truth about Carlos Santiago?"}
])

book_id = Book.first.id
book_id2 = Book.second.id
book_id3 = Book.third.id
book_id4 = Book.fourth.id
book_id5 = Book.fifth.id

User.destroy_all

User.create!([
  {username: "guest", password: "password"},
  {username: "luis", password: "password"},
  {username: "bob", password: "password"},
  {username: "jeff", password: "password"},
  {username: "maria", password: "password"}
  ])

user_id = User.first.id
user_id2 = User.second.id
user_id3 = User.third.id
user_id4 = User.fourth.id
user_id5 = User.fifth.id


bookshelf_id = Bookshelf.first.id

Bookshelfbook.destroy_all

Bookshelfbook.create!([
  {bookshelf_id: bookshelf_id, book_id: book_id},
])

Review.destroy_all

Review.create!([
  {user_id: user_id, book_id: book_id, title: "Great book!", body: "Another classic. If you don't like this series, you probably put your babel fish in the wrong hole. You are the reason that human beings are only the third most intelligent species on earth behind mice and dolphins. So long, and thanks for all the fish!", score: 4},
  {user_id: user_id2, book_id: book_id, title: "Good not great.", body: "This is not the best book ever written. It is unlikely to affect you on any deep emotional level and you probably won't spend sleepless nights just thinking about it.\n\nBut it's a simple, humourous sci-fi adventure. It won't do something for everybody but I'm a massive fan of Douglas Adams' and his sense of humour. Come on, like it or not, Adams' has some awesomely quotable sayings ", score: 3},
  {user_id: user_id3, book_id: book_id, title: "Awesome!", body: "Really wonderful humor, funny language, absurd imagery and fantastic characters. The most fun I've ever had with books. And audiobooks.. I had this on tape, the BBC version, and would listen to this in my car or on my walkman repeatedly. If you've ever wondered where those references to the number 42 come from, what it would be like to have two heads or what about the answer to life, the universe and everything - look no further. Actually, I'm gonna head off right now to get the audiobook and pick up a ringtone & notification sound from that. Sorry, got to go! Yay!", score: 5},
  {user_id: user_id4, book_id: book_id3, title: "Mind-bending", body: "I began reading some of Philip K. Dick’s short stories and quickly became hooked. His style and imagination have left an indelible mark on science fiction since and his influence is unmistakable. His novels are genius, and Ubik may be the best one I have read yet. Telling an inventive sci-fi tale that is entertaining on its surface, this is also a theological metaphor that keeps the reader thinking and trying to figure out what in the world PKD is getting at. His brilliance is compelling and his forays into a more absurd fiction only heighten his return to substantial narrative, but all is held together by his unmistakable voice. Ubik explores many of his usual themes like alienation, isolation, theological mystery and a disconnection with advancing technology. PKD is one of the more cerebral of the genre’s authors and if Heinlein, Asimov and Clarke are the “Big Three” of hard science fiction I would submit that Dick, Bradbury and Le Guin are the masters of the soft science fiction side of the house. For a PKD fan, Ubik is a must read, but it is a fine book all by itself and would be a good introduction into his world.", score: 4},
  {user_id: user_id5, book_id: book_id3, title: "Dick at his best" , body: "Once again I bow to the genius that is Philip K. Dick.. I'm envious of his madness really because it's so wonderfully controlled. I really do think that he was born in the wrong time, or maybe he's visiting from the future, or maybe he's an alien. Needless to say I loved the book. Packed full of adventure, original as always and a thoroughly enjoyable experience.", score: 5},
  {user_id: user_id, book_id: book_id3, title: "Strange but good novel", body: "This is one of Philip K. Dick's strangest novels. Those who have read his novels know that is saying a lot. But there were a few surprises for me. This is one of his wittiest novels. There are a lot of clever moments especially at the beginning. Yet sooner or later Dick will take you into the weird dimension and he does it with finesse. I do not have the patience to describe the plot. Even the Goodreads description at the top is lacking. But all the necessary ingredients... frustrated protagonists, strange alternate realities, a taste of the mystic, etc...for a Dick novel is here and they come together nicely with one of his best and most cryptic endings. This would be a great introductory read for those not familiar with this great athor. In fact, I would say if you haven't read Ubik, you haven't read Dick. Sorry. Couldn't resist. Four and a half stars.", score: 4},
  {user_id: user_id2, book_id: book_id2, title: "Trapped", body: "This reviewer is stuck in time. He is unable to escape the narrow confines of the invisible, intangible machinery mercilessly directing his life from a beginning towards an end. The walls surrounding him are dotted with windows looking out on darkened memories and foggy expectations, easing the sense of claustrophobia but offering no way out. The ceiling is crushing down on this man while he paces frantically through other people's lives and memories in hopes of shaping his own and forgetting the enormity of oblivion looming above his head. He reads book after book after book. He reads Kurt Vonnegut's Slaughterhouse-Five. He gets immersed, he gets lost in the pages. He smiles. He wonders. He tumbles. He laughs a laugh that seems to come from somewhere deep within him, telling him that everything is beautiful. A laugh that shoots up from a dark place and illuminates the universe, bathing it in colour, showing all the hidden threads in a fraction of a second. The man is consoled, recognizing that fraction as an eternity. He closes the book and looks around him. The space got bigger, the windows show a clearer picture. He sees his situation with a new light emanating from his own eyes and, looking up, notices the oppressive ceiling is no longer there. It made way for the sky, sometimes blue, sometimes painted with stars and clouds. He ruminates on this new canvas for his thoughts as a bird flies by and calls to him. Poo-tee-weet.", score: 5},
  {user_id: user_id3, book_id: book_id2, title: "Pretty good", body: "Billy Pilgrim becomes unstuck in time and experiences the events of his life out of chronological order. War and absurdity ensue. I've never read Kurt Vonnegut up until now and when Slaughterhouse-Five showed up in my cheapo ebook email a few days ago, I decided it was time. Get it? Slaughterhouse-Five is often classified as science fiction but it reads more like Kurt Vonnegut trying to make sense of his World War II experiences through a humorous (at times) science fiction story. It also seems to be a Big Important Book, due to novelly things like themes of anti-war and the absurdities that come with it. It also uses a non-linear plot structure to illustrate the timey-wimey nature of Billy's affliction. There's not really a whole lot to tell. Slaughterhouse-Five is basically a collection of non-chronological events in Billy Pilgrim's life: his experiences in World War II, his life after the war, and his abduction by the Tralfamadorians, aliens who view events in time simultaneously rather than chronologically. The bleakness and black humor go together surprisingly well, like beer and White Castles. I have to wonder, though, if Slaughterhouse-Five would be as highly regarded as it is if it didn't land on so many banned book lists over the years. Nothing like some controversy to get people to read. While it wasn't pants-shittingly awesome, I enjoyed it quite a bit and I'll likely pick up another Vonnegut book in the future. Four out of five stars. So it goes.", score: 4},
  {user_id: user_id4, book_id: book_id2, title: "Adored it", body: "No one really introduced me to this work, despite its resonant presence in the literary canon. I adore books that reek of marvelous postmodern perfume. This is one original, enthralling, always-relevant novel. Vonnegut is brave and cowardly because he makes the material his own, yet he is but scenery... his main character is an Everyman who is sooo affected by the Dresden bombings that he 'becomes unglued from time.' Yes: war is complete, utter chaos... it becomes something more powerful than physics because it is so closely related to the complete termination of life, spirit, & earthly happiness. 'Maus' reminded me of this because it mixed humor with tragedy... something super hard to pull off because the events are real. The Children's Crusade is still being fought today, & this personal statement cannot go out of style-- maybe presidents/dictators/rulers/monarchs should read it as a prerequisite?", score: 5},
  {user_id: user_id3, book_id: book_id4, title: "Recommended" , body: "For some reason this Tom Cruise movie was a blockbuster bust, but it was because of the excellent movie that I wanted to delve into this concept a bit more. After picking up the book, it's clear almost immediately that the film whitewashed the book and that destroys one of the very simple yet profound themes of this book, which I'll get to in a sec. Keiji Kiriya is a simple Japanese soldier who finds himself in a time loop, experiencing the same couple days and deaths over and over only to wake up in the barracks once more and experience it all again. The war he's in is against an alien race named the 'mimics' who are all but unstoppable, until humanity created mechanized suits, 'jackets', to be able to deal with them. And that's pretty simply it. There's some slight exposition about the aliens and the future this world finds itself in, however, it's mostly focused on Keiji and his time loops. I don't want to spoil anything too much so I'll give this warning first. In an afterword, the author, Hiroshi Sakurazaka, explains that he got the idea for this book from playing video games. You respawn so much throughout the game, you get really good at it. You also get really good at seeing the things that will be coming at you. In the end of the video game, you're praised as a hero, but really you're just an average Joe who had endless amounts of retries so you ended up getting good! And that's the brilliance of the book. There are no superpowers, unless you count the futuristic jackets and accompanying weapons. It's just an average guy, a novice even, who finds himself in a really crappy Groundhog Day scenario (at least Bill Murray's deaths were of his own volition), and decides to make the best of it by trying to get better every time. Great concept both in book and movie form and the book's different enough from the movie (or vice versa) to make it worth reading, especially given the 266 pages mmpb. The only real problem is I want more.", score: 4},
  {user_id: user_id2, book_id: book_id4, title: "Good but not groundbreaking", body: "So what do you get when you mix Groundhog Day, a war manga, and Tony Stark's suit of armor he made in a cave? You get All You Need Is Kill. Keiji Kiriya is stuck in a loop fighting aliens to the death...well to his death. Keiji has died during each of his 158 tries to get out of the loop. Bill Murray's character in Groundhog Day had it way easier than Keiji Kiriya. For me All You Need Is Kill is a book with an interesting concept that falls short once Rita Vrataski gets her own point of view. I don't want to spoil anything so I won't explain any more then saying the author should've never tried to explain how the loops work. Perhaps that isn't fair, the best way to say it is don't explain something you don't fully understand. Time travel scenarios can be as messy and annoying as stepping in poop and tracking it all around your home. Let's just say the author was likely walking around a farm with serious nasal congestion before he headed home. The story itself was intriguing prior to the Vrataski info dump. Poor Keiji has walked into a reasonable facsimile of hell. After the inevitable attempts to run away and commit suicide to escape the loops, Keiji decides to train his mind to help him win the battle. This part was enjoyable to see how he had learned to navigate his day and the battle with the proficient ease of 100 plus attempts. All I Need Is Kill felt like a case of unfulfilled potential. Perhaps I'll have to watch the movie to find out if they did a better job utilizing the concept.", score: 3},
  {user_id: user_id, book_id: book_id4, title: "It's all right", body: "20.0%	'Groundhog day mixed with Starship Troopers. Enjoying it more than I thought I would. I like the Full Metal Bitch. She's not what you think.' 65.0%	'Getting a little restless with Full Metal B*tch's backstory. I'm so ADD.' 83.0% 'They're drinking coffee.' It's ok. I was more enamored with the beginning than anything else. It'll be interesting to see how the Tom Cruise movie works out. Not hard sf. Only 200 pages though, which is good for me. I think the illustrations are missing, judging by the afterword. No, the mediocre graphic novel and the text novel are not different editions of the same book. Please fix Goodreads gods.", score: 3}
  # {user_id: user_id, book_id: book_id5, title: , body: , score: },
  # {user_id: user_id5, book_id: book_id5, title: , body: , score: },
  # {user_id: user_id4, book_id: book_id5, title: , body: , score: },
])
