Book.destroy_all

Book.create!([
  {title: "Hitchhiker's Guide To The Galaxy", author: "Douglas Adams", image_url: "http://i.imgur.com/DnbT4KB.jpg", publisher: "Del Rey", description: "Seconds before Earth is demolished to make way for a galactic freeway, Arthur Dent is plucked off the planet by his friend Ford Prefect, a researcher for the revised edition of The Hitchhiker’s Guide to the Galaxy who, for the last fifteen years, has been posing as an out-of-work actor.\n\nTogether, this dynamic pair began a journey through space aided by a galaxyful of fellow travelers: Zaphod Beeblebrox, the two-headed, three-armed, ex-hippie and totally out-to-lunch president of the galaxy; Trillian (formerly Tricia McMillan), Zaphod’s girlfriend, whom Arthur tried to pick up at a cocktail party once upon a time zone; Marvin, a paranoid, brilliant, and chronically depressed robot; and Veet Voojagig, a former graduate student obsessed with the disappearance of all the ballpoint pens he’s bought over the years.\n\nWhere are these pens? Why are we born? Why do we die? For all the answers, stick your thumb to the stars!"},
  {title: "Slaughterhouse-Five", author: "Kurt Vonnegut", image_url: "http://i.imgur.com/8pbh3jO.jpg", publisher: "Dial Press Trade Paperback", description: "Kurt Vonnegut's absurdist classic Slaughterhouse-Five introduces us to Billy Pilgrim, a man who becomes unstuck in time after he is abducted by aliens from the planet Tralfamadore. In a plot-scrambling display of virtuosity, we follow Pilgrim simultaneously through all phases of his life, concentrating on his (and Vonnegut's) shattering experience as an American prisoner of war who witnesses the firebombing of Dresden.\n\nDon't let the ease of reading fool you - Vonnegut's isn't a conventional, or simple, novel. He writes, There are almost no characters in this story, and almost no dramatic confrontations, because most of the people in it are so sick, and so much the listless playthings of enormous forces. One of the main effects of war, after all, is that people are discouraged from being characters.\n\nSlaughterhouse-Five is not only Vonnegut's most powerful book, it is also as important as any written since 1945. Like Catch- 22, it fashions the author's experiences in the Second World War into an eloquent and deeply funny plea against butchery in the service of authority. Slaughterhouse-Five boasts the same imagination, humanity, and gleeful appreciation of the absurd found in Vonnegut's other works, but the book's basis in rock-hard, tragic fact gives it a unique poignancy - and humor."},
  {title: "Ubik", author: "Philip K. Dick", image_url: "http://i.imgur.com/6Zeayhh.jpg", publisher: "Bantam Books", description: "Ubik is a 1969 science fiction novel by American writer Philip K. Dick. It is one of Dick's most acclaimed novels. It was chosen by Time magazine as one of the 100 greatest novels since 1923. In his review for Time, critic Lev Grossman described it as a deeply unsettling existential horror story, a nightmare you'll never be sure you've woken up from.\n\nThe novel takes place in the North American Confederation of 1992, where civilians regularly travel to the Moon, and psi phenomena are common. The novel's protagonist, Joe Chip, is a debt-ridden technician for Glen Runciter's prudence organization, which employs people with the ability to block psychic powers (like an anti-telepath, preventing a telepath from reading a mind) to help enforce privacy. Runciter runs the company with the assistance of his deceased wife Ella, who is kept in a state of half-life, a form of cryonic suspension that gives the deceased limited consciousness and the ability to communicate."},
  {title: "All You Need Is Kill", author: "Hiroshi Sakurazaka", image_url: "http://i.imgur.com/9u199q8.jpg", publisher: "Haikasoru", description: "There’s one thing worse than dying. It’s coming back to do it again and again… When the alien Gitai invade, Keiji Kiriya is just one of many raw recruits shoved into a suit of battle armor and sent out to kill. Keiji dies on the battlefield, only to find himself reborn each morning to fight and die again and again. On the 158th iteration though, he sees something different, something out of place: the female soldier known as the Witch of War. Is the Witch the key to Keiji’s escape, or to his final death?"},
  {title: "Harry Potter and the Sorcerer's Stone", author: "J.K. Rowling", image_url: "http://i.imgur.com/h2lCssT.jpg", publisher: "Scholastic Inc", description: "Harry Potter's life is miserable. His parents are dead and he's stuck with his heartless relatives, who force him to live in a tiny closet under the stairs. But his fortune changes when he receives a letter that tells him the truth about himself: he's a wizard. A mysterious visitor rescues him from his relatives and takes him to his new home, Hogwarts School of Witchcraft and Wizardry.\n\nAfter a lifetime of bottling up his magical powers, Harry finally feels like a normal kid. But even within the Wizarding community, he is special. He is the boy who lived: the only person to have ever survived a killing curse inflicted by the evil Lord Voldemort, who launched a brutal takeover of the Wizarding world, only to vanish after failing to kill Harry.\n\nThough Harry's first year at Hogwarts is the best of his life, not everything is perfect. There is a dangerous secret object hidden within the castle walls, and Harry believes it's his responsibility to prevent it from falling into evil hands. But doing so will bring him into contact with forces more terrifying than he ever could have imagined.\n\nFull of sympathetic characters, wildly imaginative situations, and countless exciting details, the first installment in the series assembles an unforgettable magical world and sets the stage for many high-stakes adventures to come."},
  {title: "The Caves of Steel", author: "Isaac Asimov", image_url: "http://i.imgur.com/XGxTgmj.jpg", publisher: "Voyager", description: "A millennium into the future two advancements have altered the course of human history: the colonization of the galaxy and the creation of the positronic brain. Isaac Asimov's Robot novels chronicle the unlikely partnership between a New York City detective and a humanoid robot who must learn to work together. Like most people left behind on an over-populated Earth, New York City police detective Elijah Baley had little love for either the arrogant Spacers or their robotic companions. But when a prominent Spacer is murdered under mysterious circumstances, Baley is ordered to the Outer Worlds to help track down the killer. The relationship between Life and his Spacer superiors, who distrusted all Earthmen, was strained from the start. Then he learned that they had assigned him a partner: R. Daneel Olivaw. Worst of all was that the 'R' stood for robot--and his positronic partner was made in the image and likeness of the murder victim!"},
  {title: "Console Wars: Sega, Nintendo, and the Battle that Defined a Generation", author: "Blake J. Harris", image_url: "http://i.imgur.com/FqUrwSo.jpg", publisher: "It Books", description: "Following the success of The Accidental Billionaires and Moneyball comes Console Wars—a mesmerizing, behind-the-scenes business thriller that chronicles how Sega, a small, scrappy gaming company led by an unlikely visionary and a team of rebels, took on the juggernaut Nintendo and revolutionized the video game industry.\n\nIn 1990, Nintendo had a virtual monopoly on the video game industry. Sega, on the other hand, was just a faltering arcade company with big aspirations and even bigger personalities. But that would all change with the arrival of Tom Kalinske, a man who knew nothing about videogames and everything about fighting uphill battles. His unconventional tactics, combined with the blood, sweat and bold ideas of his renegade employees, transformed Sega and eventually led to a ruthless David-and-Goliath showdown with rival Nintendo.\n\nThe battle was vicious, relentless, and highly profitable, eventually sparking a global corporate war that would be fought on several fronts: from living rooms and schoolyards to boardrooms and Congress. It was a once-in-a-lifetime, no-holds-barred conflict that pitted brother against brother, kid against adult, Sonic against Mario, and the US against Japan.\n\nBased on over two hundred interviews with former Sega and Nintendo employees, Console Wars is the underdog tale of how Kalinske miraculously turned an industry punchline into a market leader. It's the story of how a humble family man, with an extraordinary imagination and a gift for turning problems into competitive advantages, inspired a team of underdogs to slay a giant and, as a result, birth a $60 billion dollar industry."},
  {title: "BioShock: Rapture", author: "John Shirley", image_url: "http://i.imgur.com/3QPn1oA.jpg", publisher: "Tor Books", description: "It's the end of World War II. FDR's New Deal has redefined American politics. Taxes are at an all-time high. The bombing of Hiroshima and Nagasaki has brought a fear of total annihilation. The rise of secret government agencies and sanctions on business has many watching their backs. America's sense of freedom is diminishing . . . and many are desperate to take that freedom back.\n\nAmong them is a great dreamer, an immigrant who pulled himself from the depths of poverty to become one of the wealthiest and admired men in the world. That man is Andrew Ryan, and he believed that great men and women deserve better. And so he set out to create the impossible, a utopia free from government, censorship, and moral restrictions on science--where what you give is what you get. He created Rapture---the shining city below the sea.\n\nBut as we all know, this utopia suffered a great tragedy. This is the story of how it all came to be . . .and how it all ended."},
  {title: "In a Grove", author: "Ryunosuke Akutagawa", image_url: "http://i.imgur.com/TGfkxMr.jpg", publisher: "Kodansha", description: "'In a Grove' (藪の中, Yabu no Naka?) is a short story by Ryūnosuke Akutagawa, first appearing in the January 1922 edition of the Japanese literature monthly Shinchō. Akira Kurosawa used this story as the basis for his award-winning movie Rashōmon.\n\n'In a Grove' is an early modernist short story consisting of seven varying accounts of the murder of a samurai, Kanazawa no Takehiro, whose corpse has been found in a bamboo forest near Kyoto. Each section simultaneously clarifies and obfuscates what the reader knows about the murder, eventually creating a complex and contradictory vision of events that brings into question humanity's ability or willingness to perceive and transmit objective truth.\n\nThe story is often praised as being among the greatest in Japanese literature."},
  {title: "A Game of Thrones", author: "George R.R. Martin", image_url: "http://i.imgur.com/aa0ocZw.jpg", publisher: "Bantam", description: "Summers span decades. Winter can last a lifetime. And the struggle for the Iron Throne has begun.\n\nAs Warden of the north, Lord Eddard Stark counts it a curse when King Robert bestows on him the office of the Hand. His honour weighs him down at court where a true man does what he will, not what he must … and a dead enemy is a thing of beauty.\n\nThe old gods have no power in the south, Stark’s family is split and there is treachery at court. Worse, the vengeance-mad heir of the deposed Dragon King has grown to maturity in exile in the Free Cities. He claims the Iron Throne."},
  {title: "The Eye of the World", author: "Robert Jordan", image_url: "http://i.imgur.com/MivrVjT.jpg", publisher: "Tor Books", description: "The Wheel of Time turns and Ages come and go, leaving memories that become legend. Legend fades to myth, and even myth is long forgotten when the Age that gave it birth returns again. In the Third Age, an Age of Prophecy, the World and Time themselves hang in the balance. What was, what will be, and what is, may yet fall under the Shadow."},
  {title: "The Man in the High Castle", author: "Philip K. Dick", image_url: "http://i.imgur.com/2mytIvj.jpg", publisher: "Vintage", description: "It's America in 1962. Slavery is legal once again. The few Jews who still survive hide under assumed names. In San Francisco the I Ching is as common as the Yellow Pages. All because some 20 years earlier the United States lost a war, and is now occupied jointly by Nazi Germany and Japan. This harrowing, Hugo Award-winning novel is the work that established Philip K. Dick as an innovator in science fiction while breaking the barrier between science fiction and the serious novel of ideas. In it Dick offers a haunting vision of history as a nightmare from which it may just be possible to awake."},
  {title: "Machine of Death", author: "Ryan North", image_url: "http://i.imgur.com/P6c4Nvn.jpg", publisher: "Machines of Death", description: "The machine had been invented a few years ago: a machine that could tell, from just a sample of your blood, how you were going to die. It didn't give you the date and it didn't give you specifics. It just spat out a sliver of paper upon which were printed, in careful block letters, the words DROWNED or CANCER or OLD AGE or CHOKED ON A HANDFUL OF POPCORN. It let people know how they were going to die. Machine of Death tells thirty-four different stories about people who know how they will die. Prepare to have your tears jerked, your spine tingled, your funny bone tickled, your mind blown, your pulse quickened, or your heart warmed. Or better yet, simply prepare to be surprised. Because even when people do have perfect knowledge of the future, there's no telling exactly how things will turn out."},
  {title: "Dirk Gently's Holistic Detective Agency", author: "Douglas Adams", image_url: "http://i.imgur.com/VV06VwS.jpg", publisher: "Pocket Books", description: "What do a dead cat, a computer whiz-kid, an Electric Monk who believes the world is pink, quantum mechanics, a Chronologist over 200 years old, Samuel Taylor Coleridge (poet), and pizza have in common? Apparently not much; until Dirk Gently, self-styled private investigator, sets out to prove the fundamental interconnectedness of all things by solving a mysterious murder, assisting a mysterious professor, unravelling a mysterious mystery, and eating a lot of pizza – not to mention saving the entire human race from extinction along the way (at no extra charge). To find out more, read this book (better still, buy it, then read it) – or contact Dirk Gently’s Holistic Detective Agency. ‘A thumping good detective-ghost-horror-whodunnit-time travel-romantic-musical-comedy epic."},
  {title: "The New York Trilogy", author: "Paul Auster", image_url: "http://i.imgur.com/CUvZwS7.jpg", publisher: "Penguin Classics", description: "Paul Auster's signature work, The New York Trilogy, consists of three interlocking novels: City of Glass, Ghosts, and The Locked Room; haunting and mysterious tales that move at the breathless pace of a thriller."},
  {title: "Stardust", author: "Neil Gaiman", image_url: "http://i.imgur.com/kfQTdeL.jpg", publisher: "Harper Perrennial", description: "Young Tristran Thorn will do anything to win the cold heart of beautiful Victoria—even fetch her the star they watch fall from the night sky. But to do so, he must enter the unexplored lands on the other side of the ancient wall that gives their tiny village its name. Beyond that old stone wall, Tristran learns, lies Faerie—where nothing, not even a fallen star, is what he imagined. From #1 New York Times bestselling author Neil Gaiman comes a remarkable quest into the dark and miraculous—in pursuit of love and the utterly impossible."},
  {title: "American Gods", author: "Neil Gaiman", image_url: "http://i.imgur.com/h6csv6I.jpg", publisher: "William Morrow", description: "Locked behind bars for three years, Shadow did his time, quietly waiting for the day when he could return to Eagle Point, Indiana. A man no longer scared of what tomorrow might bring, all he wanted was to be with Laura, the wife he deeply loved, and start a new life. But just days before his release, Laura and Shadow's best friend are killed in an accident. With his life in pieces and nothing to keep him tethered, Shadow accepts a job from a beguiling stranger he meets on the way home, an enigmatic man who calls himself Mr. Wednesday. A trickster and a rogue, Wednesday seems to know more about Shadow than Shadow does himself. Life as Wednesday's bodyguard, driver, and errand boy is far more interesting and dangerous than Shadow ever imagined. Soon Shadow learns that the past never dies...and that beneath the placid surface of everyday life a storm is brewing - an epic war for the very soul of America - and that he is standing squarely in its path."},
  {title: "Parasyte, Volume 1", author: "Hitoshi Iwaaki", image_url: "http://i.imgur.com/7VV5EF1.jpg", publisher: "Del Rey", description: "They arrive in silence and darkness. They descend from the skies. They have a hunger for human flesh. They are everywhere. They are parasites, alien creatures who must invade - and take control of - a human host to survive. And once they have infected their victims, they can assume any deadly form they choose: monsters with giant teeth, winged demons, creatures with blades for hands. But most have chosen to conceal their lethal purpose behind ordinary human faces. So no one knows their secret - except an ordinary high school student. Shin is battling for control of his own body against an alien parasite, but can he find a way to warn humanity of the horrors to come?"},
  {title: "Mass Effect: Revelation", author: "Drew Karpyshyn", image_url: "http://i.imgur.com/33mNAFw.jpg", publisher: "Del Rey", description: "Every advanced society in the galaxy relies on the technology of the Protheans, an ancient species that vanished fifty thousand years ago. After discovering a cache of Prothean technology on Mars in 2148, humanity is spreading to the stars; the newest interstellar species, struggling to carve out its place in the greater galactic community. On the edge of colonized space, ship commander and Alliance war hero David Anderson investigates the remains of a top secret military research station; smoking ruins littered with bodies and unanswered questions. Who attacked this post and for what purpose? And where is Kahlee Sanders, the young scientist who mysteriously vanished from the base hours before her colleagues were slaughtered? Sanders is now the prime suspect, but finding her creates more problems for Anderson than it solves. Partnered with a rogue alien agent he can't trust and pursued by an assassin he can't escape, Anderson battles impossible odds on uncharted worlds to uncover a sinister conspiracy . . . one he won't live to tell about. Or so the enemy thinks."},
  {title: "Gears of War: Aspho Fields", author: "Karen Traviss", image_url: "http://i.imgur.com/XWhcHUJ.jpg", publisher: "Del Rey", description: "For the first time, fans of the blockbuster Gears of War video games get an in-depth look at Delta Squad’s toughest fighters–soldier’s soldier Marcus Fenix and rock-solid Dominic Santiago–as well as a detailed account of the pivotal battle of the Pendulum Wars. As kids, the three of them were inseparable; as soldiers, they were torn apart. Marcus Fenix and Dominic Santiago fought alongside Dom’s elder brother Carlos at Aspho Fields in the epic battle that changed the course of the Pendulum Wars. There’s a new war to fight now, a war for mankind’s very survival. But while the last human stronghold on Sera braces itself for another onslaught from the Locust Horde, ghosts come back to haunt Marcus and Dom. For Marcus–decorated war hero, convicted traitor–the return of an old comrade threatens to dredge up an agonizing secret he’s sworn to keep. As the beleaguered Gears of the Coalition of Ordered Governments take a Last Stand to save mankind from extermination, the harrowing decisions made at Aspho Fields have to be re-lived and made again. Marcus and Dom can take anything the Locust Horde throws at them–but will their friendship survive the truth about Carlos Santiago?"}
])

book_id = Book.first.id

User.destroy_all

User.create!([
  {username: "guest", password: "password"},
  {username: "luis", password: "password"}
  ])

user_id = User.first.id
user_id2 = User.second.id

bookshelf_id = Bookshelf.first.id

Bookshelfbook.destroy_all

Bookshelfbook.create!([
  {bookshelf_id: bookshelf_id, book_id: book_id},
])

Review.destroy_all

Review.create!([
  {user_id: user_id, book_id: book_id, title: "Great book!", body: "Another classic. If you don't like this series, you probably put your babel fish in the wrong hole. You are the reason that human beings are only the third most intelligent species on earth behind mice and dolphins. So long, and thanks for all the fish!", score: 4},
  {user_id: user_id2, book_id: book_id, title: "Good not great.", body: "This is not the best book ever written. It is unlikely to affect you on any deep emotional level and you probably won't spend sleepless nights just thinking about it.\n\nBut it's a simple, humourous sci-fi adventure. It won't do something for everybody but I'm a massive fan of Douglas Adams' and his sense of humour. Come on, like it or not, Adams' has some awesomely quotable sayings ", score: 3}
])
